name: env test
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  checkout:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: check file path
        run: |
          # git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          cat changed_files.txt
        
  # deploy-to-dev-env:
  #   name: deploy to dev
  #   needs: checkout
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: dev
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v4
  #     - name: heading to dev deployment
  #       run: echo "deployment successfull" >> $GITHUB_STEP_SUMMARY
        
