name: CI workflow

on:
  workflow_dispatch:
    inputs:
      majorversion:
        required: true
        type: string
      minorversion:
        required: true
        type: string

env:
  runner: "ubuntu-latest"
  majorversion: ${{ inputs.majorversion }}
  minorversion: ${{ inputs.minorversion }}
  
jobs:
  variables:
    name: exposing variables used
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ env.runner }}
      majorversion: ${{ env.majorversion }}
      minorversion: ${{ env.minorversion }}
    steps:
      - run: echo "exposing variables"
      
  inputs-used:
    name: printing current inputs used
    needs: [variables]
    runs-on: ubuntu-latest
    steps:
      - name: printing inputs used
        run: |
          echo -e "### current inputs used" >> $GITHUB_STEP_SUMMARY
          echo "| input_name | value |" >> $GITHUB_STEP_SUMMARY
          echo "| ------------- | ----------- |"  >> $GITHUB_STEP_SUMMARY
          echo "| runner | ${{needs.variables.outputs.runner }} |" >> $GITHUB_STEP_SUMMARY
          echo "| majorversion | ${{needs.variables.outputs.majorversion }} |" >> $GITHUB_STEP_SUMMARY
          echo "| minorversion | ${{needs.variables.outputs.minorversion }} |" >> $GITHUB_STEP_SUMMARY
         
  generate-build-version:
    name: generate-build-version
    needs: [variables,inputs-used]
    uses: hemanthkatkozu/shared-workflows/.github/workflows/generating-build-version.yaml@master
    with:
      runner: ${{needs.variables.outputs.runner }}
      major_version: ${{needs.variables.outputs.majorversion }}
      minor_version: ${{needs.variables.outputs.minorversion }}
    secrets: inherit

  install-dependencies:
    name: install-dependencies
    needs: [variables,generate-build-version]
    uses: hemanthkatkozu/shared-workflows/.github/workflows/build-artifact.yaml@master
    with:
      runner: ${{needs.variables.outputs.runner }}
    secrets: inherit
  
  test-cases:
    name: test-cases
    needs: [variables,install-dependencies]
    uses: hemanthkatkozu/shared-workflows/.github/workflows/testcases.yaml@master
    with:
      runner: ${{needs.variables.outputs.runner }}
    secrets: inherit
    
  image-build-push:
    name: image-build-push
    needs: [variables,generate-build-version,test-cases]
    uses: hemanthkatkozu/shared-workflows/.github/workflows/image_build_push.yaml@master
    with:
      runner: ${{needs.variables.outputs.runner }}
      image_version: ${{needs.generate-build-version.outputs.image_version }}
    secrets: inherit
